name: CD

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # 수동 실행도 가능

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up GPG secret key
        run: |
          echo "${{ secrets.SIGNING_SECRET_KEY_RING_BASE64 }}" | base64 -d > /home/runner/.gnupg/secring.gpg
          chmod 600 /home/runner/.gnupg/secring.gpg

      - name: Setup gradle.properties
        run: |
          cat <<EOF > gradle.properties
          mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}
          mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          signing.keyId=${{ secrets.SIGNING_KEY_ID }}
          signing.password=${{ secrets.SIGNING_PASSWORD }}
          signing.secretKeyRingFile=/home/runner/.gnupg/secring.gpg
          EOF

      - name: Publish to Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache --stacktrace